name: Build and deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y \
            build-essential \
            libssl-dev \
            libreadline-dev \
            zlib1g-dev \
            libsqlite3-dev \
            libxml2-dev \
            libxslt1-dev \
            libcurl4-openssl-dev \
            libffi-dev \
            git \
            wget

      - name: Install Bundler and Jekyll
        run: |
          gem install bundler jekyll

      - name: Setup Bundler config
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build and deploy site
        run: |
          jekyll build --config _config.yml
          cp -r _site/* /docs/
